// <auto-generated />
namespace Pearl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class role : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(role));
        
        string IMigrationMetadata.Id
        {
            get { return "201912080352287_role"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
